version: '3'

services:
  node:
    image: 'node:9'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 3000:3000
    command: 'npm start'
